# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/config_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_config_dialog(object):
    def setupUi(self, config_dialog):
        config_dialog.setObjectName("config_dialog")
        config_dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        config_dialog.resize(233, 330)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(config_dialog.sizePolicy().hasHeightForWidth())
        config_dialog.setSizePolicy(sizePolicy)
        config_dialog.setMinimumSize(QtCore.QSize(0, 0))
        config_dialog.setMaximumSize(QtCore.QSize(99999, 99999))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/graph_2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        config_dialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(config_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.load_from_file_button = QtWidgets.QPushButton(config_dialog)
        self.load_from_file_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.load_from_file_button.setIcon(icon1)
        self.load_from_file_button.setObjectName("load_from_file_button")
        self.horizontalLayout.addWidget(self.load_from_file_button)
        self.save_to_file_button = QtWidgets.QPushButton(config_dialog)
        self.save_to_file_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_to_file_button.setIcon(icon2)
        self.save_to_file_button.setObjectName("save_to_file_button")
        self.horizontalLayout.addWidget(self.save_to_file_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.add_cmd_button = QtWidgets.QPushButton(config_dialog)
        self.add_cmd_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_cmd_button.setIcon(icon3)
        self.add_cmd_button.setDefault(True)
        self.add_cmd_button.setObjectName("add_cmd_button")
        self.horizontalLayout.addWidget(self.add_cmd_button)
        self.remove_cmd_button = QtWidgets.QPushButton(config_dialog)
        self.remove_cmd_button.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/minus2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.remove_cmd_button.setIcon(icon4)
        self.remove_cmd_button.setObjectName("remove_cmd_button")
        self.horizontalLayout.addWidget(self.remove_cmd_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.cmd_edit = QtWidgets.QLineEdit(config_dialog)
        self.cmd_edit.setInputMask("")
        self.cmd_edit.setObjectName("cmd_edit")
        self.verticalLayout.addWidget(self.cmd_edit)
        self.cmd_list_widget = QtWidgets.QListWidget(config_dialog)
        self.cmd_list_widget.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.cmd_list_widget.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.cmd_list_widget.setObjectName("cmd_list_widget")
        self.verticalLayout.addWidget(self.cmd_list_widget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.ok_button = QtWidgets.QPushButton(config_dialog)
        self.ok_button.setObjectName("ok_button")
        self.horizontalLayout_2.addWidget(self.ok_button)
        self.cancel_button = QtWidgets.QPushButton(config_dialog)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout_2.addWidget(self.cancel_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(config_dialog)
        QtCore.QMetaObject.connectSlotsByName(config_dialog)

    def retranslateUi(self, config_dialog):
        _translate = QtCore.QCoreApplication.translate
        config_dialog.setWindowTitle(_translate("config_dialog", "Конфигурация измерения"))
        self.cmd_edit.setPlaceholderText(_translate("config_dialog", "Введите команду"))
        self.ok_button.setText(_translate("config_dialog", "Ок"))
        self.cancel_button.setText(_translate("config_dialog", "Отмена"))
import icons_rc
